# config.yml

index_names:
  - unit_number
  - time_cycles

setting_names:
  - setting_1
  - setting_2
  - setting_3

sensor_names:
  - s_1
  - s_2
  - s_3
  - s_4
  - s_5
  - s_6
  - s_7
  - s_8
  - s_9
  - s_10
  - s_11
  - s_12
  - s_13
  - s_14
  - s_15
  - s_16
  - s_17
  - s_18
  - s_19
  - s_20
  - s_21

col_names:
  - unit_number
  - time_cycles
  - setting_1
  - setting_2
  - setting_3
  - s_1
  - s_2
  - s_3
  - s_4
  - s_5
  - s_6
  - s_7
  - s_8
  - s_9
  - s_10
  - s_11
  - s_12
  - s_13
  - s_14
  - s_15
  - s_16
  - s_17
  - s_18
  - s_19
  - s_20
  - s_21

sensor_dictionary:
  s_1: "(Fan inlet temperature) (◦R)"
  s_2: "(LPC outlet temperature) (◦R)"
  s_3: "(HPC outlet temperature) (◦R)"
  s_4: "(LPT outlet temperature) (◦R)"
  s_5: "(Fan inlet Pressure) (psia)"
  s_6: "(bypass-duct pressure) (psia)"
  s_7: "(HPC outlet pressure) (psia)"
  s_8: "(Physical fan speed) (rpm)"
  s_9: "(Physical core speed) (rpm)"
  s_10: "(Engine pressure ratio(P50/P2)"
  s_11: "(HPC outlet Static pressure) (psia)"
  s_12: "(Ratio of fuel flow to Ps30) (pps/psia)"
  s_13: "(Corrected fan speed) (rpm)"
  s_14: "(Corrected core speed) (rpm)"
  s_15: "(Bypass Ratio)"
  s_16: "(Burner fuel-air ratio)"
  s_17: "(Bleed Enthalpy)"
  s_18: "(Required fan speed)"
  s_19: "(Required fan conversion speed)"
  s_20: "(High-pressure turbines Cool air flow)"
  s_21: "(Low-pressure turbines Cool air flow)"
